--- 
:username: mockuser
:password: mockpassword
:storage_snapshot_id: snap-72a5401b
:driver_name: gogrid
:instances_count: 2
:flavor_arch: i386
:storage_snapshot_state: AVAILABLE
:realm_id: us
:instance_1_name: ami-e4b6538d
:image_owner: "mockuser"
:storage_snapshot_count: "2"
:realm_state: AVAILABLE
:instance_2_name: ami-e4b6538d
:image_arch: i386
:storage_volume_id: vol-60957009
:storage_volume_instance: i-123f1234
:realm_count: 1
:instance_image_id: 1
:image_id: 1
:storage_volume_state: AVAILABLE
:flavor_id: server-with-512mb-ram
:instance_realm: us
:image_count: 2
:storage_volume_count: 0
:flavor_count: 3
