--- 
:storage_snapshot_id: snap2
:driver_name: mock
:instances_count: 180
:flavor_arch: x86_64
:storage_snapshot_state: AVAILABLE
:realm_id: us
:instance_1_name: 1268827277 testing instance
:image_owner: fedoraproject
:storage_snapshot_count: "2"
:realm_state: AVAILABLE
:instance_2_name: 1268827278 testing instance
:image_arch: i386
:storage_volume_id: vol2
:realm_count: 2
:instance_image_id: img2
:image_id: img2
:storage_volume_state: AVAILABLE
:flavor_id: m1-small
:instance_realm: us
:image_count: 3
:storage_volume_count: 2
:flavor_count: 5
